on: [push, pull_request]

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get corelib
        run: git clone -b lucas/multiline_diag https://github.com/0xLucqs/cairo

      - name: Install toolchain
        run: rustup show

      - uses: Swatinem/rust-cache@v2
      
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

      - name: Run cargo test
        run: CORELIB_PATH="$(pwd)/cairo/corelib/src" cargo test
        
      - name: Run cargo fmt
        run: rustup toolchain install nightly && rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt && cargo +nightly fmt -- --check
